[tool.poetry]
name = "sorobn"
version = "0.1.0"
description = "Bayesian networks in Python"
authors = ["Max Halford <maxhalford25@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
vose = { git = "https://github.com/MaxHalford/vose.git" }
numpy = "^1.24.2"
pandas = "^1.5.3"

[tool.poetry.dev-dependencies]
graphviz = "*"
pytest = "*"
scikit-learn = "*"

# TODO: turn back on when poetry sorts it out
# [tool.poetry.group.examples.dependencies]
# daft = "*"
# matplotlib = "*"
# scikit-learn = "*"

# [tool.poetry.group.gui.dependencies]
# graphviz = "*"
# streamlit = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
sorobn = 'sorobn:cli_hook'
